import test from "node:test";
import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { readFileSync } from "node:fs";
const read = (path) => readFileSync(new URL(`../${path}`, import.meta.url), "utf8");

test("Linux installer parses as POSIX shell", () => { execFileSync("sh", ["-n", "scripts/install.sh"], { cwd: new URL("../", import.meta.url) }); });
test("JobRequest owns exact hardware selections", () => { const main = read("src/main.ts"); const rust = read("src-tauri/src/lib.rs"); assert.match(main, /groupHardware: hardwareMode\("groupHardwarePolicy"\)/); assert.match(main, /trailHardware: hardwareMode\("trailHardwarePolicy"\)/); assert.match(main, /timelapseHardware: hardwareMode\("timelapseHardwarePolicy"\)/); assert.doesNotMatch(rust, /HARDWARE_POLICIES|set_hardware_policies/); assert.match(rust, /request\.group_hardware/); });
test("launch barrier workaround is gone", () => { assert.doesNotMatch(read("src/bootstrap.ts"), /LaunchStateSync/); });
test("workspace images never receive full source URLs", () => { const main = read("src/main.ts"); const thumbs = read("src/photo-thumbnail-manager.ts"); assert.doesNotMatch(main, /convertFileSrc\(photo\.path\)/); assert.match(main, /data-thumb-path/); assert.match(thumbs, /invoke<ThumbnailResult>\("get_thumbnail"/); assert.doesNotMatch(thumbs, /createImageBitmap|ImageDecoder|fetch\(source/); });
test("group previews share native thumbnail manager", () => { const parity = read("src/workspace-parity.ts"); assert.match(parity, /thumb\.dataset\.thumbPath = preview\.path/); assert.doesNotMatch(parity, /convertFileSrc\(path\)/); });
test("Process and Workspace share one canonical output state", () => { const main = read("src/main.ts"); const sync = read("src/engine-group-sync.ts"); assert.match(main, /function setOutputPath\(value: string\): void \{/); assert.match(main, /outputPath = value/); assert.match(main, /#workspaceOutputPath/); assert.match(main, /#workspacePickOutput[\s\S]*?pickOutputFolder\(\)/); assert.match(main, /#pickOutput[\s\S]*?pickOutputFolder\(\)/); assert.match(main, /return buildOutputPath\(mode, outputPath/); assert.match(sync, /document\.querySelector<HTMLElement>\("#outputPath"\)/); assert.doesNotMatch(sync, /document\.querySelector<HTMLElement>\("#workspaceOutputPath"\)/); });
test("manual review command is above Frames, groups are below Frames", () => { const studio = read("src/studio-editor.ts"); assert.match(studio, /controls\.insertAdjacentElement\("afterend", commandBar\)/); assert.match(studio, /layout\.insertAdjacentElement\("afterend", groupPanel\)/); assert.match(studio, /groupPanel\.insertAdjacentElement\("afterend", editorPanel\)/); });
test("group mass selection and delete controls exist", () => { const studio = read("src/studio-editor.ts"); for (const id of ["studioSelectAllGroups", "studioClearGroupSelection", "studioInvertGroupSelection", "studioDeleteGroup", "studioMergeGroups"]) assert.match(studio, new RegExp(id)); assert.match(studio, /Frames become Ungrouped; source files are never deleted/); assert.match(studio, /selectedGroupIds/); assert.match(studio, /groupUndo/); });

test("thumbnail IPC is RAW-aware and avoids asset URL regressions", () => { const rust = read("src-tauri/src/lib.rs"); const thumbs = read("src/photo-thumbnail-manager.ts"); assert.match(rust, /render_thumbnail_with_engine/); assert.match(rust, /tihulu-thumbnail/); assert.match(rust, /data:image\/jpeg;base64/); assert.match(thumbs, /result\.dataUrl/); assert.doesNotMatch(thumbs, /convertFileSrc/); });
test("workspace no longer loads the selection pulse render loop", () => { const bootstrap = read("src/bootstrap.ts"); assert.doesNotMatch(bootstrap, /StudioEditorSelectionSync/); const css = read("src/workspace-parity.css"); assert.match(css, /position: absolute/); assert.match(css, /padding-left: 68px/); });
test("Linux desktop identity matches packaged COSMIC app id and verifies CUDA", () => { const install = read("scripts/install.sh"); assert.match(install, /WAYLAND_APP_ID="gui4tihulu-star-trail"/); assert.match(install, /applications\/\$WAYLAND_APP_ID\.desktop/); assert.match(install, /Icon=\$WAYLAND_APP_ID/); assert.match(install, /StartupWMClass=\$WAYLAND_APP_ID/); assert.match(install, /rm -f \"\$HOME\/\.local\/share\/applications\/\$TAURI_IDENTIFIER\.desktop\"/); assert.match(install, /HOME\/tihulu-star-trail\/\.venv\/bin\/tihulu/); assert.match(install, /cupy-cuda13x\[ctk\]/); assert.match(install, /engine_gpu_ready/); assert.match(install, /engine_supports_runtime \"\$ENGINE_PATH\"/); assert.doesNotMatch(install, /engine_supports_policies/); assert.match(install, /NVIDIA GPU runtime: verified/); });
test("managed engine launchers strip AppImage runtime poisoning", () => { const install = read("scripts/install.sh"); assert.match(install, /GUI4TIHULU_APPIMAGE_SAFE_WRAPPER/); assert.match(install, /install_appimage_safe_engine_wrappers/); assert.match(install, /unset PYTHONHOME PYTHONPATH LD_LIBRARY_PATH QT_PLUGIN_PATH/); assert.match(install, /unset GTK_DATA_PREFIX GTK_EXE_PREFIX GTK_PATH/); assert.match(install, /clean_path=/); assert.match(install, /\"\$\{APPDIR:-\}\"\/\*/); assert.match(install, /export PATH="\$VENV\/bin:\$HOME\/\.local\/bin:/); });
test("workspace class mutations do not rebuild group cards", () => { const studio = read("src/studio-editor.ts"); assert.match(studio, /structureChanged/); assert.match(studio, /queueSelectionSync/); assert.match(studio, /renderEditorForSelection\(\)/); assert.doesNotMatch(studio, /MutationObserver\(\(\) => queueMicrotask\(syncFromMainGrid\)/); });
